### PR TITLE
Update colors

### PR DESCRIPTION
**Pull request by Azeezah**

### CODE REVIEW

**Comment by Rhaypapenfuzz** [comment]
can you attach a picture to this pull request

**Comment by Azeezah** [comment]
https://imgur.com/a/p0hW0kO

**Comment by Rhaypapenfuzz** [comment]
I don't think these color choices are great

**Comment by Rhaypapenfuzz** [comment]
Let me know if you come up with other interesting options

**Comment by Azeezah** [comment]
Let's just roll back the pink and blue before the presentation tomorrow then.

**Review by swarnim151 — APPROVED** [review]

**Pull request merged**
