### PR TITLE
Explore and profile page UI improvement

### PR DESCRIPTION
**Pull request by Rhaypapenfuzz**
Also made the star like feature and fixed some old bugs

### CODE REVIEW

**Comment by Rhaypapenfuzz** [comment]
Screen Shot 2020-04-27 at 8 09 42 PM
Screen Shot 2020-04-27 at 8 09 34 PM

**Comment by Rhaypapenfuzz** [comment]
We can change the colors later. Just needed to visualize it

**Comment by Azeezah** [comment]
Could you put the add grid button with the rest of the cards in the profile page like they are in the explore page?

**Comment by Rhaypapenfuzz** [comment]
> Could you put the add grid button with the rest of the cards in the profile page like they are in the explore page?

I thought it didn't looked good when I did that on the profile. Plus I wanted the profile to focus more on the user's cards and the big card was distracting. I will try and readjust that to look small and find a better position to put it on the upper part of the page

**Review by kricheso — APPROVED** [review]
Great work!

**Pull request merged**
